(define deck
    (list
        (list
            (list "6C" "9S")
            "AH"
            "AS"
            "TH"
            "4C"
            "QH"
            "9C"
            "3H"
            "AS"
            "7D"
            "3D"
            "TD"    
    )
    (list
        (list "TC" "QS")
            "8D"
            "AS"
            "TH"
            "4C"
            "QH"
            "9C"
            "3H"
            "AS"
            "7D"
            "3D"
            "TD"
    )
    (list
        (list "AC" "AS")
            "8H"
            "7S"
            "6H"
            "5C"
            "4H"
            "3C"
            "2H"
            "AS"
            "7D"
            "3D"
            "TD"
    )
    (list
        (list "7C" "9S")
            "AD"
            "7S"
            "4H"
            "QC"
            "9H"
            "KC"
            "3H"
            "AS"
            "7D"
            "3D"
            "TD"
    )
    (list
        (list "6C" "4S")
            "7H"
            "3D"
            "AS"
            "TH"
            "4C"
            "QH"
            "9C"
            "3H"
            "AS"
            "7D"
            "TD"
    )
    (list
        (list "3C" "QS")
            "3D"
            "AS"
            "TH"
            "4C"
            "QH"
            "9C"
            "3H"
            "AS"
            "8D"
            "7D"
            "TD"
    )
    (list
        (list "AC" "AS")
            "8H"
            "2S"
            "2H"
            "AS"
            "6H"
            "5C"
            "4H"
            "3C"
            "7D"
            "3D"
            "TD"
    )
    (list
        (list "QC" "9S")
            "9H"
            "AD"
            "4H"
            "3D"
            "7S"
            "QC"
            "KC"
            "3H"
            "AS"
            "7D"
            "TD"
    )
    (list
        (list "JC" "KS")
            "TC"
            "9S"
            "8H"
            "2H"
            "AS"
            "6H"
            "4H"
            "3C"
            "7D"
            "3D"
            "TD"
    )
    (list
        (list "QC" "4S")
            "QC"
            "4H"
            "3D"
            "7S"
            "KC"
            "9H"
            "3H"
            "AS"
            "7D"
            "AD"
            "TD"
        )
    )
)